apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-highkali-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dr-highkali-role
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get","list","watch"]
